From pytorch/pytorch

RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    apt-get -y update && \
    apt-get install -y libsm-dev python3-pip software-properties-common wget ffmpeg && \
    mkdir -p /root/.torch/models && \
    mkdir -p /data/models
    
RUN pip install -r requirements.txt -i https://pypi.doubanio.com/simple
RUN pip install flask pillow scikit-image requests gunicorn -i https://pypi.doubanio.com/simple


ADD . /data/

WORKDIR /data


EXPOSE 5000

ENTRYPOINT ["python3"]

CMD ["app.py"]
